os:
- linux

language: php

php:
- '7.2'

before_script:
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
script:
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  #  - vendor/bin/phpunit --coverage-clover=coverage.xml


after_success:
- bash <(curl -s https://codecov.io/bash)
